pub mod blake2b;
pub mod blake2bp;
pub mod blake3;
pub mod k12;
pub mod parallelhash;
pub mod registry;
pub mod shake256;
pub mod turboshake;
pub mod xxh3;

pub use blake2b::Blake2bHasher;
pub use blake2bp::Blake2bpHasher;
pub use blake3::Blake3Hasher;
pub use k12::K12Hasher;
pub use parallelhash::ParallelHash256Hasher;
pub use registry::Algorithm;
pub use shake256::Shake256Hasher;
pub use turboshake::TurboShake256Hasher;
pub use xxh3::Xxh3Expander;
